### ISSUE TITLE
`pyshp` version lock limits usage with `cartopy`

### ISSUE THREAD

**Issue by gcoyle83** [pyswmm/swmmio#234]
## Issue description
This may be a very edge case issue for you all, and I want to lead with a thanks for the work on this library. That said, I tend to use `cartopy` to develop maps for displaying geospatial data. Cartopy requires `pyshp>=2.3`, while `swmmio` appears to be locked to `pyshp==2.1.0`, which is going on six years old. Understanding your core objective is maintaining your own library, not compatibility with arbitrary others, is it a big ask to update to the latest `pyshp` to resolve this?

## To reproduce
Build env with basic dependencies:
```yaml
name: test_env
channels:
 - conda-forge
dependencies:
 - python==3.11 
 - cartopy 
 - jupyter 
 - matplotlib>=3.6 
 - pip 
 - pyproj>=3.3.1 
 - pyshp>=2.3 
 - shapely>=1.8 
 - pip:
    - pyswmm[swmm5.2.3]
```
Then run example from cartopy docs:
```python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
ax = plt.axes(projection=ccrs.PlateCarree())
ax.coastlines()
plt.show()
```
This should work. Add `swmmio` to pip installs, and then it will not work, throwing a `ShapefileException` error due to pyshp version lock.
